name: CI

on:
  # push:
  #   branches:
  #     - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  install:
    uses: reallifedeveloper/github-workflows/.github/workflows/maven-install.yaml@main
