name: Build and publish a Maven site

on:
  workflow_run:
    workflows:
      - CD
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    uses: reallifedeveloper/github-workflows/.github/workflows/maven-site.yaml@main
    secrets: inherit
