name: Build and publish a Maven site

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    uses: reallifedeveloper/github-workflows/.github/workflows/maven-site.yaml@main
    secrets: inherit
