name: Test workflow triggers

on:
  push:
    tags:
      - v*
  workflow_dispatch:

  jobs:
    test:
      runs-on: ubuntu-latest
      - name: Test release tag trigger
        run: |
          echo "Hello, World"